/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/fortune/basic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["calculate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/fortune": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/fortune/compatibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quoteCompatibility"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/fortune/love": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quoteLove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/fortune/overall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quoteOverall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/fortune/sinsal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quoteSinsal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/fortune/wealth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quoteWealth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{quoteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reading-purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reading-purchases/compatibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purchaseCompatibility"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reading-purchases/love": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purchaseLove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reading-purchases/overall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purchaseOverall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reading-purchases/sinsal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purchaseSinsal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reading-purchases/wealth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purchaseWealth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/compatibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompatibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/compatibility/{readingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompatibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/love": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLove"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/love/{readingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLove"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/overall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOverall"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/overall/{readingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverall"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/sinsal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSinsal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/sinsal/{readingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSinsal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/wealth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/wealth/{readingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readings/{readingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/top-up-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTopUpOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/top-up-orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopUpOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseBasicSajuResult: {
            data?: components["schemas"]["BasicSajuResult"];
            traceId?: string;
        };
        ApiResponseCategoryListResponse: {
            data?: components["schemas"]["CategoryListResponse"];
            traceId?: string;
        };
        ApiResponseCategoryPurchaseResponseCompatibilityReadingResponse: {
            data?: components["schemas"]["CategoryPurchaseResponseCompatibilityReadingResponse"];
            traceId?: string;
        };
        ApiResponseCategoryPurchaseResponseLoveReadingResponse: {
            data?: components["schemas"]["CategoryPurchaseResponseLoveReadingResponse"];
            traceId?: string;
        };
        ApiResponseCategoryPurchaseResponseOverallReadingResponse: {
            data?: components["schemas"]["CategoryPurchaseResponseOverallReadingResponse"];
            traceId?: string;
        };
        ApiResponseCategoryPurchaseResponseSinsalReadingResponse: {
            data?: components["schemas"]["CategoryPurchaseResponseSinsalReadingResponse"];
            traceId?: string;
        };
        ApiResponseCategoryPurchaseResponseWealthReadingResponse: {
            data?: components["schemas"]["CategoryPurchaseResponseWealthReadingResponse"];
            traceId?: string;
        };
        ApiResponseCategoryQuoteResponse: {
            data?: components["schemas"]["CategoryQuoteResponse"];
            traceId?: string;
        };
        ApiResponseCompatibilityReadingResponse: {
            data?: components["schemas"]["CompatibilityReadingResponse"];
            traceId?: string;
        };
        ApiResponseFundedQuoteResponse: {
            data?: components["schemas"]["FundedQuoteResponse"];
            traceId?: string;
        };
        ApiResponseLoveReadingResponse: {
            data?: components["schemas"]["LoveReadingResponse"];
            traceId?: string;
        };
        ApiResponseOrderResponse: {
            data?: components["schemas"]["OrderResponse"];
            traceId?: string;
        };
        ApiResponseOverallReadingResponse: {
            data?: components["schemas"]["OverallReadingResponse"];
            traceId?: string;
        };
        ApiResponsePurchaseResponse: {
            data?: components["schemas"]["PurchaseResponse"];
            traceId?: string;
        };
        ApiResponseReadingListResponse: {
            data?: components["schemas"]["ReadingListResponse"];
            traceId?: string;
        };
        ApiResponseReadingResponse: {
            data?: components["schemas"]["ReadingResponse"];
            traceId?: string;
        };
        ApiResponseSinsalReadingResponse: {
            data?: components["schemas"]["SinsalReadingResponse"];
            traceId?: string;
        };
        ApiResponseSuneungQuoteResponse: {
            data?: components["schemas"]["SuneungQuoteResponse"];
            traceId?: string;
        };
        ApiResponseWalletResponse: {
            data?: components["schemas"]["WalletResponse"];
            traceId?: string;
        };
        ApiResponseWealthReadingResponse: {
            data?: components["schemas"]["WealthReadingResponse"];
            traceId?: string;
        };
        /** @description Supply personId only, or complete raw birth information; the two input forms are exclusive. */
        BasicSajuRequest: {
            birthDate?: string;
            birthTime?: string;
            birthTimeUnknown?: boolean;
            /** @enum {string} */
            calendarType?: "SOLAR" | "LUNAR";
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "UNSPECIFIED";
            leapMonth?: boolean;
            /** Format: uuid */
            personId?: string;
        };
        BasicSajuResult: {
            birthTimeKnown?: boolean;
            calculationVersion?: string;
            dayMaster?: components["schemas"]["Stem"];
            fiveElements?: components["schemas"]["FiveElements"];
            pillars?: components["schemas"]["Pillars"];
            relations?: components["schemas"]["Relations"];
            tenGods?: components["schemas"]["TenGods"];
            twelveStages?: components["schemas"]["TwelveStages"];
        };
        Branch: {
            /** @enum {string} */
            element?: "WOOD" | "FIRE" | "EARTH" | "METAL" | "WATER";
            hangul?: string;
            hanja?: string;
            /** @enum {string} */
            yinYang?: "YANG" | "YIN";
        };
        CategoryListResponse: {
            hasNext?: boolean;
            items?: components["schemas"]["CategoryReadingSummary"][];
            nextCursor?: string;
        };
        CategoryPurchaseResponseCompatibilityReadingResponse: {
            /** Format: int32 */
            balance?: number;
            calculationVersion?: string;
            charged?: components["schemas"]["Charged"];
            contentVersion?: string;
            generationVersion?: string;
            /** Format: uuid */
            purchaseId?: string;
            reading?: components["schemas"]["CompatibilityReadingResponse"];
            /** Format: uuid */
            readingId?: string;
            reused?: boolean;
            status?: string;
        };
        CategoryPurchaseResponseLoveReadingResponse: {
            /** Format: int32 */
            balance?: number;
            calculationVersion?: string;
            charged?: components["schemas"]["Charged"];
            contentVersion?: string;
            generationVersion?: string;
            /** Format: uuid */
            purchaseId?: string;
            reading?: components["schemas"]["LoveReadingResponse"];
            /** Format: uuid */
            readingId?: string;
            reused?: boolean;
            status?: string;
        };
        CategoryPurchaseResponseOverallReadingResponse: {
            /** Format: int32 */
            balance?: number;
            calculationVersion?: string;
            charged?: components["schemas"]["Charged"];
            contentVersion?: string;
            generationVersion?: string;
            /** Format: uuid */
            purchaseId?: string;
            reading?: components["schemas"]["OverallReadingResponse"];
            /** Format: uuid */
            readingId?: string;
            reused?: boolean;
            status?: string;
        };
        CategoryPurchaseResponseSinsalReadingResponse: {
            /** Format: int32 */
            balance?: number;
            calculationVersion?: string;
            charged?: components["schemas"]["Charged"];
            contentVersion?: string;
            generationVersion?: string;
            /** Format: uuid */
            purchaseId?: string;
            reading?: components["schemas"]["SinsalReadingResponse"];
            /** Format: uuid */
            readingId?: string;
            reused?: boolean;
            status?: string;
        };
        CategoryPurchaseResponseWealthReadingResponse: {
            /** Format: int32 */
            balance?: number;
            calculationVersion?: string;
            charged?: components["schemas"]["Charged"];
            contentVersion?: string;
            generationVersion?: string;
            /** Format: uuid */
            purchaseId?: string;
            reading?: components["schemas"]["WealthReadingResponse"];
            /** Format: uuid */
            readingId?: string;
            reused?: boolean;
            status?: string;
        };
        CategoryQuoteResponse: {
            /** Format: int32 */
            balanceAfter: number | null;
            charged: components["schemas"]["Charged"];
            /** Format: date-time */
            expiresAt: string;
            productCode: string;
            productOption: string;
            questionKey: string;
            /** Format: uuid */
            quoteId: string;
            recommendedTopUp: string | null;
            /** Format: int32 */
            shortage: number;
            /** Format: int32 */
            walletBalance: number;
        };
        CategoryReadingSummary: {
            counterpartDisplayName?: string;
            /** Format: date-time */
            createdAt?: string;
            generationMode?: string;
            /** Format: uuid */
            id?: string;
            productOption?: string;
            questionKey?: string;
            subjectDisplayName?: string;
            summary?: components["schemas"]["SectionContent"];
        };
        Charged: {
            /** Format: int32 */
            amount?: number;
            currency?: string;
        };
        CompatibilityPurchaseRequest: {
            /** Format: uuid */
            counterpartPersonId: string;
            /** Format: uuid */
            personId: string;
            /** @enum {string} */
            productOption: "READING_ONLY" | "READING_WITH_TALISMAN";
            questionKey: string;
            /** Format: uuid */
            quoteId: string;
            /** @enum {string} */
            relationType: "FAMILY" | "FRIEND" | "LOVER" | "CRUSH" | "WORK_SCHOOL" | "OTHER";
        };
        CompatibilityQuoteRequest: {
            /** Format: uuid */
            counterpartPersonId: string;
            /** Format: uuid */
            personId: string;
            /** @enum {string} */
            productOption: "READING_ONLY" | "READING_WITH_TALISMAN";
            questionKey: string;
            /** @enum {string} */
            relationType: "FAMILY" | "FRIEND" | "LOVER" | "CRUSH" | "WORK_SCHOOL" | "OTHER";
        };
        CompatibilityReadingResponse: {
            communication?: components["schemas"]["SectionContent"];
            counterpart?: components["schemas"]["Counterpart"];
            matchConflict?: components["schemas"]["SectionContent"];
            matchStrength?: components["schemas"]["SectionContent"];
            meta?: components["schemas"]["ReadingMeta"];
            missingElement?: components["schemas"]["SectionContent"];
            relationshipTip?: components["schemas"]["SectionContent"];
            summary?: components["schemas"]["SectionContent"];
        };
        Counterpart: {
            displayName?: string;
            /** Format: uuid */
            personId?: string;
            relationType?: string;
        };
        CreateRequest: {
            productCode: string;
        };
        Event: {
            /** Format: date */
            date?: string;
            type?: string;
        };
        FiveElements: {
            counts?: {
                [key: string]: number;
            };
            dominant?: ("WOOD" | "FIRE" | "EARTH" | "METAL" | "WATER")[];
            missing?: ("WOOD" | "FIRE" | "EARTH" | "METAL" | "WATER")[];
        };
        FundedQuoteResponse: {
            /** Format: int32 */
            balanceAfter: number | null;
            charged: components["schemas"]["Charged"];
            /** Format: date-time */
            expiresAt: string;
            productCode: string;
            /** Format: uuid */
            quoteId: string;
            recommendedTopUp: string | null;
            /** Format: int32 */
            shortage: number;
            /** Format: int32 */
            walletBalance: number;
        };
        GeneratedSection: {
            content?: string;
            /** @enum {string} */
            key?: "SUMMARY" | "CURRENT_FLOW" | "GOOD_PERIOD" | "CAUTION" | "ACTION_TIP" | "RELATIONSHIPS" | "STUDY_AND_WORK" | "WEALTH_FLOW" | "CONDITION" | "LUCKY_POINT" | "INCOME" | "SPENDING_CAUTION" | "MATCH_STRENGTH" | "MATCH_CONFLICT" | "COMMUNICATION" | "RELATIONSHIP_TIP" | "SPECIAL_STARS" | "BALANCING_SPECIAL_STARS" | "MISSING_ELEMENT" | "EXAM_DAY" | "EXAM_PERIODS" | "FOCUS" | "MEAL" | "PREPARATION" | "ANXIETY_MANAGEMENT";
            sourceFactKeys?: string[];
        };
        LoveReadingResponse: {
            actionTip?: components["schemas"]["SectionContent"];
            caution?: components["schemas"]["SectionContent"];
            currentFlow?: components["schemas"]["SectionContent"];
            goodPeriod?: components["schemas"]["SectionContent"];
            meta?: components["schemas"]["ReadingMeta"];
            missingElement?: components["schemas"]["SectionContent"];
            summary?: components["schemas"]["SectionContent"];
        };
        OrderResponse: {
            /** Format: int32 */
            amount: number;
            /** Format: int32 */
            bonusShellAmount: number;
            /** Format: int32 */
            creditedShellAmount: number;
            currency: string;
            /** Format: uuid */
            orderId: string;
            orderName: string;
            /** Format: int32 */
            paidShellAmount: number;
            productCode: string;
            /** @enum {string} */
            status: "CREATED" | "PAYMENT_PENDING" | "PAID" | "CREDITED" | "FAILED" | "CANCELED" | "REFUNDED";
        };
        OverallReadingResponse: {
            condition?: components["schemas"]["SectionContent"];
            currentFlow?: components["schemas"]["SectionContent"];
            luckyPoint?: components["schemas"]["SectionContent"];
            meta?: components["schemas"]["ReadingMeta"];
            missingElement?: components["schemas"]["SectionContent"];
            relationships?: components["schemas"]["SectionContent"];
            studyAndWork?: components["schemas"]["SectionContent"];
            summary?: components["schemas"]["SectionContent"];
            wealthFlow?: components["schemas"]["SectionContent"];
        };
        Pillar: {
            branch?: components["schemas"]["Branch"];
            display?: string;
            stem?: components["schemas"]["Stem"];
        };
        Pillars: {
            day?: components["schemas"]["Pillar"];
            hour?: components["schemas"]["Pillar"];
            month?: components["schemas"]["Pillar"];
            year?: components["schemas"]["Pillar"];
        };
        PurchaseRequest: {
            /** Format: uuid */
            counterpartPersonId?: string;
            /** @enum {string} */
            fortuneType?: "OVERALL" | "LOVE" | "WEALTH" | "COMPATIBILITY" | "SINSAL" | "SUNEUNG";
            /** Format: uuid */
            personId: string;
            /** @enum {string} */
            productOption?: "READING_ONLY" | "READING_WITH_TALISMAN";
            questionKey?: string;
            /** Format: uuid */
            quoteId: string;
            /** @enum {string} */
            relationType?: "FAMILY" | "FRIEND" | "LOVER" | "CRUSH" | "WORK_SCHOOL" | "OTHER";
        };
        PurchaseResponse: {
            /** Format: int32 */
            balance?: number;
            calculationVersion?: string;
            charged?: components["schemas"]["Charged"];
            contentVersion?: string;
            generationVersion?: string;
            /** Format: uuid */
            purchaseId?: string;
            reading?: components["schemas"]["ReadingResponse"];
            /** Format: uuid */
            readingId?: string;
            reused?: boolean;
            status?: string;
        };
        QuoteRequest: {
            /** Format: uuid */
            counterpartPersonId?: string;
            /** @enum {string} */
            fortuneType?: "OVERALL" | "LOVE" | "WEALTH" | "COMPATIBILITY" | "SINSAL" | "SUNEUNG";
            /** Format: uuid */
            personId: string;
            /** @enum {string} */
            productOption?: "READING_ONLY" | "READING_WITH_TALISMAN";
            questionKey?: string;
            /** @enum {string} */
            relationType?: "FAMILY" | "FRIEND" | "LOVER" | "CRUSH" | "WORK_SCHOOL" | "OTHER";
        };
        ReadingListResponse: {
            hasNext?: boolean;
            items?: components["schemas"]["ReadingSummary"][];
            nextCursor?: string;
        };
        ReadingMeta: {
            calculationVersion?: string;
            contentVersion?: string;
            /** Format: date-time */
            createdAt?: string;
            disclaimers?: string[];
            generationMode?: string;
            generationVersion?: string;
            /** Format: uuid */
            id?: string;
            productOption?: string;
            questionKey?: string;
            subjectDisplayName?: string;
            talisman?: components["schemas"]["Talisman"];
        };
        ReadingResponse: {
            calculationVersion?: string;
            contentVersion?: string;
            counterpart?: components["schemas"]["Counterpart"];
            /** Format: date-time */
            createdAt?: string;
            disclaimers?: string[];
            event?: components["schemas"]["Event"];
            fortuneType?: string;
            generationMode?: string;
            generationVersion?: string;
            /** Format: uuid */
            id?: string;
            productOption?: string;
            questionKey?: string;
            sections?: components["schemas"]["GeneratedSection"][];
            subjectDisplayName?: string;
            talisman?: components["schemas"]["Talisman"];
        };
        ReadingSummary: {
            counterpartDisplayName?: string;
            /** Format: date-time */
            createdAt?: string;
            fortuneType?: string;
            generationMode?: string;
            /** Format: uuid */
            id?: string;
            productOption?: string;
            questionKey?: string;
            subjectDisplayName?: string;
        };
        Relation: {
            display?: string;
            positions?: ("YEAR" | "MONTH" | "DAY" | "HOUR")[];
            /** @enum {string} */
            type?: "STEM_COMBINATION" | "STEM_CLASH" | "BRANCH_COMBINATION" | "BRANCH_TRINE" | "BRANCH_HALF_TRINE" | "BRANCH_CLASH" | "BRANCH_PUNISHMENT" | "BRANCH_HARM" | "BRANCH_DESTRUCTION";
        };
        Relations: {
            values?: components["schemas"]["Relation"][];
        };
        SectionContent: {
            content?: string;
            sourceFactKeys?: string[];
        };
        SinsalReadingResponse: {
            balancingGuide?: components["schemas"]["SectionContent"];
            meta?: components["schemas"]["ReadingMeta"];
            missingElement?: components["schemas"]["SectionContent"];
            specialStars?: components["schemas"]["SectionContent"];
            summary?: components["schemas"]["SectionContent"];
        };
        StandardPurchaseRequest: {
            /** Format: uuid */
            personId: string;
            /** @enum {string} */
            productOption: "READING_ONLY" | "READING_WITH_TALISMAN";
            questionKey: string;
            /** Format: uuid */
            quoteId: string;
        };
        StandardQuoteRequest: {
            /** Format: uuid */
            personId: string;
            /** @enum {string} */
            productOption: "READING_ONLY" | "READING_WITH_TALISMAN";
            questionKey: string;
        };
        Stem: {
            /** @enum {string} */
            element?: "WOOD" | "FIRE" | "EARTH" | "METAL" | "WATER";
            hangul?: string;
            hanja?: string;
            /** @enum {string} */
            yinYang?: "YANG" | "YIN";
        };
        SuneungQuoteResponse: {
            /** Format: int32 */
            balanceAfter: number | null;
            charged: components["schemas"]["Charged"];
            event: components["schemas"]["Event"];
            /** Format: date-time */
            expiresAt: string;
            productCode: string;
            /** Format: uuid */
            quoteId: string;
            recommendedTopUp: string | null;
            /** Format: int32 */
            shortage: number;
            /** Format: int32 */
            walletBalance: number;
        };
        Talisman: {
            /** Format: uuid */
            id?: string;
            status?: string;
        };
        TenGodPosition: {
            /** @enum {string} */
            branch?: "DAY_MASTER" | "FRIEND" | "ROB_WEALTH" | "EATING_GOD" | "HURTING_OFFICER" | "INDIRECT_WEALTH" | "DIRECT_WEALTH" | "SEVEN_KILLINGS" | "DIRECT_OFFICER" | "INDIRECT_RESOURCE" | "DIRECT_RESOURCE";
            /** @enum {string} */
            stem?: "DAY_MASTER" | "FRIEND" | "ROB_WEALTH" | "EATING_GOD" | "HURTING_OFFICER" | "INDIRECT_WEALTH" | "DIRECT_WEALTH" | "SEVEN_KILLINGS" | "DIRECT_OFFICER" | "INDIRECT_RESOURCE" | "DIRECT_RESOURCE";
        };
        TenGods: {
            day?: components["schemas"]["TenGodPosition"];
            hour?: components["schemas"]["TenGodPosition"];
            month?: components["schemas"]["TenGodPosition"];
            year?: components["schemas"]["TenGodPosition"];
        };
        TwelveStages: {
            /** @enum {string} */
            day?: "BIRTH" | "BATH" | "CROWN" | "OFFICIAL" | "PROSPERITY" | "DECLINE" | "SICKNESS" | "DEATH" | "TOMB" | "EXTINCTION" | "CONCEPTION" | "NOURISHMENT";
            /** @enum {string} */
            hour?: "BIRTH" | "BATH" | "CROWN" | "OFFICIAL" | "PROSPERITY" | "DECLINE" | "SICKNESS" | "DEATH" | "TOMB" | "EXTINCTION" | "CONCEPTION" | "NOURISHMENT";
            /** @enum {string} */
            month?: "BIRTH" | "BATH" | "CROWN" | "OFFICIAL" | "PROSPERITY" | "DECLINE" | "SICKNESS" | "DEATH" | "TOMB" | "EXTINCTION" | "CONCEPTION" | "NOURISHMENT";
            /** @enum {string} */
            year?: "BIRTH" | "BATH" | "CROWN" | "OFFICIAL" | "PROSPERITY" | "DECLINE" | "SICKNESS" | "DEATH" | "TOMB" | "EXTINCTION" | "CONCEPTION" | "NOURISHMENT";
        };
        WalletResponse: {
            /** Format: int32 */
            balance: number;
            /** Format: int32 */
            bonusBalance: number;
            currency: string;
            /** Format: int32 */
            paidBalance: number;
        };
        WealthReadingResponse: {
            actionTip?: components["schemas"]["SectionContent"];
            goodPeriod?: components["schemas"]["SectionContent"];
            income?: components["schemas"]["SectionContent"];
            meta?: components["schemas"]["ReadingMeta"];
            missingElement?: components["schemas"]["SectionContent"];
            spendingCaution?: components["schemas"]["SectionContent"];
            summary?: components["schemas"]["SectionContent"];
            wealthFlow?: components["schemas"]["SectionContent"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    calculate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasicSajuRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBasicSajuResult"];
                };
            };
        };
    };
    quote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSuneungQuoteResponse"];
                };
            };
        };
    };
    quoteCompatibility: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompatibilityQuoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryQuoteResponse"];
                };
            };
        };
    };
    quoteLove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandardQuoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryQuoteResponse"];
                };
            };
        };
    };
    quoteOverall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandardQuoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryQuoteResponse"];
                };
            };
        };
    };
    quoteSinsal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandardQuoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryQuoteResponse"];
                };
            };
        };
    };
    quoteWealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandardQuoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryQuoteResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quoteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFundedQuoteResponse"];
                };
            };
        };
    };
    purchase: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePurchaseResponse"];
                };
            };
        };
    };
    purchaseCompatibility: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompatibilityPurchaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryPurchaseResponseCompatibilityReadingResponse"];
                };
            };
        };
    };
    purchaseLove: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandardPurchaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryPurchaseResponseLoveReadingResponse"];
                };
            };
        };
    };
    purchaseOverall: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandardPurchaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryPurchaseResponseOverallReadingResponse"];
                };
            };
        };
    };
    purchaseSinsal: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandardPurchaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryPurchaseResponseSinsalReadingResponse"];
                };
            };
        };
    };
    purchaseWealth: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandardPurchaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryPurchaseResponseWealthReadingResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                fortuneType?: "OVERALL" | "LOVE" | "WEALTH" | "COMPATIBILITY" | "SINSAL" | "SUNEUNG";
                personId?: string;
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReadingListResponse"];
                };
            };
        };
    };
    listCompatibility: {
        parameters: {
            query?: {
                personId?: string;
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryListResponse"];
                };
            };
        };
    };
    getCompatibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                readingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCompatibilityReadingResponse"];
                };
            };
        };
    };
    listLove: {
        parameters: {
            query?: {
                personId?: string;
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryListResponse"];
                };
            };
        };
    };
    getLove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                readingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoveReadingResponse"];
                };
            };
        };
    };
    listOverall: {
        parameters: {
            query?: {
                personId?: string;
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryListResponse"];
                };
            };
        };
    };
    getOverall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                readingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOverallReadingResponse"];
                };
            };
        };
    };
    listSinsal: {
        parameters: {
            query?: {
                personId?: string;
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryListResponse"];
                };
            };
        };
    };
    getSinsal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                readingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSinsalReadingResponse"];
                };
            };
        };
    };
    listWealth: {
        parameters: {
            query?: {
                personId?: string;
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryListResponse"];
                };
            };
        };
    };
    getWealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                readingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWealthReadingResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                readingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReadingResponse"];
                };
            };
        };
    };
    createTopUpOrder: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponse"];
                };
            };
        };
    };
    getTopUpOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWalletResponse"];
                };
            };
        };
    };
}
